[image]
name = "dev"
base = "dev-latest"
image = "ghcr.io/bethropolis/podbox:dev-latest"

[image.packages]
manager = "pacman"
install = ["fastfetch", "fish"]

[container]
name = "dev"
home = "~/containers/dev"
shell = "/usr/bin/fish"

[integration]
wayland = true
audio = true
gpu = true
notify = true
clipboard = true
xdg_open = true
dbus = true
sync_themes = true
sync_icons = true
sync_fonts = true

[integration.xdg_dirs]
documents = true
downloads = true
pictures = true
music = true
videos = true
desktop = true
projects = true

[lifecycle]
quadlet = true
autostart = true
auto_update = true
