[image]
name = "fedora"
base = "fedora-latest"
image = "ghcr.io/bethropolis/podbox:fedora-latest"

[image.packages]
manager = "dnf"
install = ["fastfetch", "fish"]

[container]
name = "fedora"
home = "~/containers/fedora"
shell = "/usr/bin/fish"

[integration]
wayland = true
audio = true
gpu = true
notify = true
clipboard = true
xdg_open = true
dbus = true
ssh_agent = true
gpg_agent = true
sync_themes = true
sync_icons = true
sync_fonts = true

[integration.xdg_dirs]
documents = true
downloads = true
pictures = true
music = true
videos = true
desktop = true
projects = true

[dbus]
preset = "gnome"

[lifecycle]
quadlet = true
autostart = true
auto_update = true
