ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG TARGETPLATFORM

ENV PODBOX_CONTAINER=1

COPY $TARGETPLATFORM/podbox-guest /usr/local/bin/podbox-guest

RUN pacman -Syu --noconfirm fish fastfetch \
 && pacman -Scc --noconfirm

RUN chmod +x /usr/local/bin/podbox-guest

ENTRYPOINT ["/usr/local/bin/podbox-guest", "--entry"]
CMD ["/usr/bin/fish"]
