FROM cachyos/cachyos:latest

COPY podmgr-guest /usr/local/bin/podmgr-guest

LABEL podmgr.guest_version="0.2.0"
LABEL podmgr.protocol_version="1"
LABEL podmgr.integration.wayland="true"
LABEL podmgr.integration.audio="true"
LABEL podmgr.integration.gpu="enabled"
LABEL podmgr.integration.dbus="true"
LABEL podmgr.shell="/bin/bash"
LABEL podmgr.default_shell="/bin/bash"

ENTRYPOINT ["/usr/local/bin/podmgr-guest", "--entry"]
CMD ["/bin/bash"]
