[image]
name = "fedora"
base = "fedora-latest"
prebuilt = true
prebuilt_registry = "ghcr.io"
prebuilt_repo = "bethropolis/podmgr-images"

[container]
name = "fedora"
home = "~/containers/fedora"
shell = "/usr/bin/fish"

[integration]
wayland = true
audio = true
gpu = true
sync_themes = true
sync_icons = true
sync_fonts = true

[integration.xdg_dirs]
documents = true
downloads = true
pictures = true
music = true
videos = true
desktop = true

[lifecycle]
quadlet = true
autostart = true
auto_update = true
