[image]
name = "gaming"
base = "cachy-latest"
prebuilt = true
prebuilt_registry = "ghcr.io"
prebuilt_repo = "bethropolis/podmgr-images"

[image.packages]
manager = "pacman"
install = ["fastfetch", "btop", "fish"]

[container]
name = "gaming"
home = "~/containers/gaming"
shell = "/usr/bin/fish"

[integration]
wayland = true
audio = true
gpu = true
sync_themes = true
sync_icons = true
sync_fonts = true

[integration.xdg_dirs]
documents = true
downloads = true
pictures = true
music = true
videos = true
desktop = true
projects = true

[lifecycle]
quadlet = true
autostart = true
auto_update = true
