ARG BASE_IMAGE=docker.io/cachyos/cachyos:latest
FROM ${BASE_IMAGE}

ARG TARGETPLATFORM

ENV PODBOX_CONTAINER=1

COPY $TARGETPLATFORM/podbox-guest /usr/local/bin/podbox-guest

RUN pacman -Syu --noconfirm \
    fish \
    git \
    base-devel \
    neovim \
    ripgrep \
    fd \
    zoxide \
    mise \
 && pacman -Scc --noconfirm \
 && localedef -i en_US -f UTF-8 en_US.UTF-8

RUN chmod +x /usr/local/bin/podbox-guest

ENTRYPOINT ["/usr/local/bin/podbox-guest", "--entry"]
CMD ["/usr/bin/fish"]
