FROM fedora:44

RUN dnf install -y fish && \
    dnf clean all

COPY podmgr-guest /usr/local/bin/podmgr-guest

LABEL podmgr.guest_version="0.2.0"
LABEL podmgr.protocol_version="1"
LABEL podmgr.integration.wayland="true"
LABEL podmgr.integration.audio="true"
LABEL podmgr.integration.gpu="enabled"
LABEL podmgr.integration.dbus="true"
LABEL podmgr.shell="/usr/bin/fish"
LABEL podmgr.default_shell="/usr/bin/fish"

ENTRYPOINT ["/usr/local/bin/podmgr-guest", "--entry"]
CMD ["/usr/bin/fish"]
