ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG TARGETPLATFORM

ENV PODBOX_CONTAINER=1

COPY $TARGETPLATFORM/podbox-guest /usr/local/bin/podbox-guest

RUN dnf install -y fish fastfetch glibc-langpack-en \
 && dnf clean all

RUN chmod +x /usr/local/bin/podbox-guest

ENTRYPOINT ["/usr/local/bin/podbox-guest", "--entry"]
CMD ["/usr/bin/fish"]
